name: dartlove
description: A starting point for Dart libraries or applications.
version: 0.0.1
author: novemberisms <briansarfati@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: ^1.1.6

dev_dependencies:
  test: ^1.0.0
